### ISSUE TITLE
Fetch not working on Windows

### ISSUE THREAD

**Issue by tuxagon** [tuxagon/yata-cli#14]
Encountered a runtime error on windows for v1.0

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x67d9db]

goroutine 1 [running]:
golang.org/x/oauth2.(*Config).AuthCodeURL(0x0, 0x811ce2, 0xb, 0xc042067880, 0x1, 0x1, 0xc042009df0, 0x0)
        /home/kbogner/go/src/golang.org/x/oauth2/oauth2.go:128 +0x5b
yata-cli/yata.GoogleDriveManager.tokenFromWeb(0xc042045a10, 0x0, 0x0, 0x9aaf40)
        /home/kbogner/go/src/yata-cli/yata/servermanager.go:209 +0xb1
yata-cli/yata.GoogleDriveManager.getClient(0xc042045a10, 0x0, 0x9affc0, 0xc0420084b0, 0x0, 0x7ea940, 0xc042045a01, 0xc04
2009da0)
        /home/kbogner/go/src/yata-cli/yata/servermanager.go:192 +0xec
yata-cli/yata.(*GoogleDriveManager).setService(0xc042009da0)
        /home/kbogner/go/src/yata-cli/yata/servermanager.go:184 +0x7e
yata-cli/yata.NewServerManager(0x0, 0x5, 0x80fa40)
        /home/kbogner/go/src/yata-cli/yata/servermanager.go:56 +0x8a
yata-cli/cmd.serverFetch(0x0, 0x812230, 0xc)
        /home/kbogner/go/src/yata-cli/cmd/fetch.go:24 +0x36
yata-cli/cmd.Fetch(0xc042036640, 0x0, 0xc042036640)
        /home/kbogner/go/src/yata-cli/cmd/fetch.go:14 +0x7d
github.com/urfave/cli.HandleAction(0x78dfc0, 0x825540, 0xc042036640, 0xc042012a00, 0x0)
        /home/kbogner/go/src/github.com/urfave/cli/app.go:485 +0xdb
github.com/urfave/cli.Command.Run(0x80fa4a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x81eced, 0x2b, 0x0, ...)
        /home/kbogner/go/src/github.com/urfave/cli/command.go:207 +0xb75
github.com/urfave/cli.(*App).Run(0xc04201f520, 0xc042044240, 0x3, 0x3, 0x0, 0x0)
        /home/kbogner/go/src/github.com/urfave/cli/app.go:250 +0x7d7
main.main()
        /home/kbogner/go/src/yata-cli/main.go:75 +0x1280
```

**Comment by tuxagon** [comment]
Non-issue. I should follow my own advice and add the `client_secret.json` file to the config.
